# fly.toml app configuration file generated for Site Studio
# Docs: https://fly.io/docs/reference/configuration/

app = "site-studio"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  min_machines_running = 0

# If you want to run with local filesystem (not recommended for prod), uncomment and create a volume
# [[mounts]]
#   source = "site_studio_data"
#   destination = "/data"

