#!/usr/bin/env node
/**
 * Reads all template directories under packages/app/templates/ and generates
 * a TypeScript module (src/lib/template-content.ts) with their file contents
 * as string constants. This is needed because Cloudflare Workers can't read
 * the filesystem at runtime.
 *
 * Run: node --import tsx scripts/bundle-templates.ts
 *   or: bun scripts/bundle-templates.ts
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATES_DIR = join(__dirname, "../templates");
const OUTPUT_FILE = join(__dirname, "../src/lib/template-content.ts");

async function main() {
  const templateDirs = (await readdir(TEMPLATES_DIR, { withFileTypes: true }))
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const entries: string[] = [];

  for (const templateId of templateDirs) {
    const dir = join(TEMPLATES_DIR, templateId);
    const files = (await readdir(dir, { withFileTypes: true }))
      .filter((f) => f.isFile())
      .map((f) => f.name);

    const fileEntries: string[] = [];

    for (const fileName of files) {
      const content = await readFile(join(dir, fileName), "utf-8");
      // Escape backticks and ${} in template literals
      const escaped = content
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$\{/g, "\\${");
      fileEntries.push(`    ${JSON.stringify(fileName)}: \`${escaped}\``);
    }

    entries.push(`  ${JSON.stringify(templateId)}: {\n${fileEntries.join(",\n")}\n  }`);
  }

  const output = `// AUTO-GENERATED by scripts/bundle-templates.ts — do not edit manually
// Contains all template file contents as string constants for Cloudflare Workers runtime.

export const TEMPLATE_FILES = {\n${entries.join(",\n")}\n} as const satisfies Readonly<Record<string, Readonly<Record<string, string>>>>;\n`;

  await writeFile(OUTPUT_FILE, output, "utf-8");
  console.log(`Generated ${OUTPUT_FILE} with ${templateDirs.length} templates`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
