// Test stub for SvelteKit's virtual `$app/paths` module. The real module is
// generated by `sveltekit()` at build time; under vitest we only use the
// `svelte()` plugin, so we alias `$app/paths` to this stub. `base` is '' in
// tests, matching the default (root) deployment.
export const base = '';
export const assets = '';

export function resolveRoute(id: string): string {
	return id;
}
